services:

  # Set bind-mounted folder ownership for zhjx services
  zhjx-permissions:
    image: zhjx-images.tencentcloudcr.com/library/permissions:1.0.0
    restart: on-failure
    entrypoint: []
    command: ["sh", "/usr/local/bin/setowners-zhjx.sh"]
    volumes:
      # Command script
      - ../apps/permissions/setowners-zhjx.sh:/usr/local/bin/setowners-zhjx.sh:ro
      # Bind-mounted volumes to set ownership
      - ../../data/rabbitmq:/mounts/rabbitmq
      - ../../data/redis:/mounts/redis
      - ../../data/minio:/mounts/minio
      - ../../data/elasticsearch:/mounts/elasticsearch
      - ../../data/kafka:/mounts/kafka
      - ../../data/kkfileview:/mounts/kkfileview
      - ../../data/mysql:/mounts/mysql


  zhjx-mysql:
    image: docker.io/mysql:8.4.7
    init: true
    hostname: zhjx-mysql
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=STj1ZAHGUYJS
    ports:
      - "3306:3306"
    volumes:
      - ../../data/mysql:/var/lib/mysql
    networks:
      - zhjx-network
    depends_on:
      - zhjx-permissions

  zhjx-nginx:
    image: zhjx-images.tencentcloudcr.com/library/nginx:1.23.2
    init: true
    hostname: zhjx-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "../build/nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "../build/nginx/portal_ly-sky_com.key:/data/nginx/portal_ly-sky_com.key"
      - "../build/nginx/portal_ly-sky_com.crt:/data/nginx/portal_ly-sky_com.crt"
    networks:
      - zhjx-network
    depends_on: []

  zhjx-rabbitmq:
    image: zhjx-images.tencentcloudcr.com/library/rabbitmq:3.8-management-delayed
    hostname: zhjx-rabbitmq
    init: true
    restart: unless-stopped
    user: "999:999"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=LUPwgc3qoGIT
    volumes:
      - ../../data/rabbitmq:/var/lib/rabbitmq
    networks:
      - zhjx-network
    depends_on:
      - zhjx-permissions

  zhjx-redis:
    image: zhjx-images.tencentcloudcr.com/library/redis:5.0.7
    hostname: zhjx-redis
    init: true
    restart: unless-stopped
    user: "999:999"
    volumes:
      - ../../data/redis:/data
    networks:
      - zhjx-network
    depends_on:
      - zhjx-permissions

  zhjx-nacos:
    image: zhjx-images.tencentcloudcr.com/library/nacos-server:2.0.2
    init: true
    hostname: zhjx-nacos
    restart: unless-stopped
    environment:
      - PREFER_HOST_MODE=hostname
      - MODE=standalone
      - SPRING_DATASOURCE_PLATFORM=mysql
      - MYSQL_SERVICE_HOST=192.168.0.2
      - MYSQL_SERVICE_DB_NAME=nacos
      - MYSQL_SERVICE_PORT=3306
      - MYSQL_SERVICE_USER=root
      - MYSQL_SERVICE_PASSWORD=STj1ZAHGUYJS
      - DEBUG=true
    networks:
      - zhjx-network
    depends_on:
      - zhjx-permissions
      - zhjx-redis

  zhjx-sentinel:
    image: zhjx-images.tencentcloudcr.com/library/sentinel-dashboard:1.8.5
    init: true
    hostname: zhjx-sentinel
    restart: unless-stopped
    depends_on:
      - zhjx-nacos
    networks:
      - zhjx-network

  zhjx-fileview:
    image: zhjx-images.tencentcloudcr.com/library/keking/kkfileview:3.1
    init: true
    hostname: zhjx-fileview
    restart: unless-stopped
    user: "1000:1000"
    networks:
      - zhjx-network
    environment:
      KK_FILE_DIR: "/data/file"
      KK_BASE_URL: "http://127.0.0.1/preview/"
      KK_CONTEXT_PATH: "/preview/"
    volumes:
      - ../../data/kkfileview:/data/file
    depends_on:
      - zhjx-permissions

  zhjx-minio:
    image: zhjx-images.tencentcloudcr.com/library/minio:RELEASE.2022-08-02T23-59-16Z.fips
    init: true
    hostname: zhjx-minio
    restart: unless-stopped
    user: "1000:1000"
    ports:
      - "59000:9000"
      - "59001:9001"
    command: server --console-address :9001 /data
    environment:
      MINIO_ROOT_USER: "admin"
      MINIO_ROOT_PASSWORD: "ErqOl4kwLwcg"
      MINIO_SERVER_URL: "http://192.168.0.2:59000"
    networks:
      - zhjx-network
    volumes:
      - ../../data/minio:/data
    depends_on:
      - zhjx-permissions

  zhjx-emqx:
    image: zhjx-images.tencentcloudcr.com/library/emqx:4.4.19
    init: true
    hostname: zhjx-emqx
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "8081:8081"
      - "8083:8083"
      - "8883:8883"
      - "8084:8084"
      - "18083:18083"
    environment:
      - EMQX_PROTOCOL_MODULES="emqx_web_hook,emqx_recon,emqx_retainer,emqx_management,emqx_dashboard"
      - EMQX_LISTENER__WSS__EXTERNAL__ACCEPTORS=4
      - EMQX_LISTENER__WSS__EXTERNAL__SSL=true
      - EMQX_LISTENER__WSS__EXTERNAL__SSL_OPTS="certfile:/etc/emqx/portal_ly-sky_com.crt,keyfile:/etc/emqx/portal_ly-sky_com.key"
    volumes:
      - "../build/nginx/portal_ly-sky_com.key:/etc/emqx/portal_ly-sky_com.key"
      - "../build/nginx/portal_ly-sky_com.crt:/etc/emqx/portal_ly-sky_com.crt"
    networks:
      - zhjx-network
    depends_on: []

  zhjx-kafka:
    image: zhjx-images.tencentcloudcr.com/library/bitnami/kafka:3.5
    init: true
    hostname: zhjx-kafka
    restart: unless-stopped
    user: "1001:1001"
    environment:
      KAFKA_ENABLE_KRAFT: "yes"
      KAFKA_CFG_NODE_ID: 1
      KAFKA_CFG_PROCESS_ROLES: broker,controller
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://zhjx-kafka:9092
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 1@zhjx-kafka:9093
    volumes:
      - ../../data/kafka:/bitnami/kafka
    networks:
      - zhjx-network
    depends_on:
      - zhjx-permissions

  zhjx-elasticsearch:
    init: true
    hostname: zhjx-elasticsearch
    image: zhjx-images.tencentcloudcr.com/library/elasticsearch:7.14.0-ik
    restart: unless-stopped
    user: "1000:1000"
    volumes:
      - ../../data/elasticsearch:/usr/share/elasticsearch/data
    environment:
      ES_JAVA_OPTS: "-Xmx1024m -Xms1024m -Xlog:gc*,gc+age=trace,safepoint:file=/usr/share/elasticsearch/logs/gc.log:utctime,pid,tags:filecount=32,filesize=64m"
      discovery.type: single-node
      http.cors.enabled: "true"
      http.cors.allow-origin: "*"
    networks:
      - zhjx-network
    depends_on:
      - zhjx-permissions

networks:
  zhjx-network:
    external: true
