
x-ui-environment:
  &ui-environment
  spring.cloud.inetutils.preferred-networks: 10.10.0
  API_GATEWAY_URL: "http://ly-ac-gateway-svc:50000"
  SCHOOL_ID: "demo-school"
  API_TENANT_URL: "http://192.168.0.2:50004"
  API_OBJECT_STORAGE_URL: "http://192.168.0.2:50007"
  ISPOT_APP_SOURCE: "v9wsePOjui4ZqjHv4vCBpyfqKK1P3MhWtQRpHGA49CR2nNK7LaIEgzhd73bKYLhn"

x-svc-environment:
  &svc-environment
  discovery: "zhjx-nacos"
  nacosGroup: "DEFAULT_GROUP"
  mysqlHost: "192.168.0.2"
  mysqlPort: 3306
  mysqlUser: "root"
  mysqlPassword: "STj1ZAHGUYJS"
  serverAddr: "http://zhjx-nacos:8848"

services:
  ly-ac-auth-ui:
    image: zhjx-images.tencentcloudcr.com/ly-sky.com/ly-ac-auth-ui:latest
    init: true
    restart: unless-stopped
    environment: *ui-environment
    networks:
      - zhjx-network
    depends_on:
      - zhjx-nacos

  ly-ac-console-ui:
    image: zhjx-images.tencentcloudcr.com/ly-sky.com/ly-ac-console-ui:latest
    init: true
    restart: unless-stopped
    environment: *ui-environment
    networks:
      - zhjx-network
    depends_on:
      - zhjx-nacos

  ly-ac-gateway-svc:
    image: zhjx-images.tencentcloudcr.com/ly-sky.com/ly-ac-gateway-svc:latest
    restart: unless-stopped
    networks:
      - zhjx-network
    environment:
      - nacosServerAddr=http://zhjx-nacos:8848
      - nacosGroup=DEFAULT_GROUP
      - nacosUser=nacos
      - nacosPassword=LUPwgc3qoGIT
      - profilActive=dev
      - sentinelDashboard=zhjx-sentinel:8858
    entrypoint: [""]
    command: ["sh", "-c", "java -Xms1G -Xmx2G -XX:MaxMetaspaceSize=256M -XX:+UseG1GC -XX:MaxGCPauseMillis=200 -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/tmp -XX:+UseStringDeduplication -jar /usr/local/app.jar"]
    depends_on:
      - zhjx-nacos
      - zhjx-sentinel

  ly-ac-job-admin-svc:
    image: zhjx-images.tencentcloudcr.com/ly-sky.com/ly-ac-job-admin-svc:latest
    init: true
    restart: unless-stopped
    environment: *svc-environment
    networks:
      - zhjx-network
    depends_on:
      - zhjx-nacos
      - zhjx-redis

  ly-ac-object-storage-svc:
    image: zhjx-images.tencentcloudcr.com/ly-sky.com/ly-ac-object-storage-svc:latest
    init: true
    restart: unless-stopped
    environment: *svc-environment
    networks:
      - zhjx-network
    entrypoint: [""]
    command: ["sh", "-c", "java -Xms1G -Xmx2G -XX:MaxMetaspaceSize=256M -XX:+UseG1GC -XX:MaxGCPauseMillis=200 -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/tmp -XX:+UseStringDeduplication -jar /usr/local/app.jar"]
    depends_on:
      - zhjx-nacos
      - zhjx-minio

  ly-ac-admin-svc:
    image: zhjx-images.tencentcloudcr.com/ly-sky.com/ly-ac-admin-svc:latest
    init: true
    restart: unless-stopped
    environment: *svc-environment
    networks:
      - zhjx-network
    entrypoint: [""]
    command: ["sh", "-c", "java -Xms1G -Xmx2G -XX:MaxMetaspaceSize=256M -XX:+UseG1GC -XX:MaxGCPauseMillis=200 -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/tmp -XX:+UseStringDeduplication -jar /usr/local/app.jar"]
    depends_on:
      - zhjx-nacos
      - zhjx-redis

  ly-ac-auth-svc:
    image: zhjx-images.tencentcloudcr.com/ly-sky.com/ly-ac-auth-svc:latest
    init: true
    restart: unless-stopped
    environment: *svc-environment
    networks:
      - zhjx-network
    entrypoint: [""]
    command: ["sh", "-c", "java -Xms1G -Xmx2G -XX:MaxMetaspaceSize=256M -XX:+UseG1GC -XX:MaxGCPauseMillis=200 -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/tmp -XX:+UseStringDeduplication -jar /usr/local/app.jar"]
    depends_on:
      - zhjx-nacos
      - zhjx-redis

  ly-ac-basic-data-svc:
    image: zhjx-images.tencentcloudcr.com/ly-sky.com/ly-ac-basic-data-svc:latest
    init: true
    restart: unless-stopped
    environment: *svc-environment
    networks:
      - zhjx-network
    entrypoint: [""]
    command: ["sh", "-c", "java -Xms1G -Xmx2G -XX:MaxMetaspaceSize=256M -XX:+UseG1GC -XX:MaxGCPauseMillis=200 -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/tmp -XX:+UseStringDeduplication -jar /usr/local/app.jar"]
    depends_on:
      - zhjx-nacos
      - zhjx-redis

  ly-ac-user-svc:
    image: zhjx-images.tencentcloudcr.com/ly-sky.com/ly-ac-user-svc:latest
    init: true
    restart: unless-stopped
    environment: *svc-environment
    networks:
      - zhjx-network
    entrypoint: [""]
    command: ["sh", "-c", "java -Xms1G -Xmx2G -XX:MaxMetaspaceSize=256M -XX:+UseG1GC -XX:MaxGCPauseMillis=200 -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/tmp -XX:+UseStringDeduplication -jar /usr/local/app.jar"]
    depends_on:
      - zhjx-nacos
      - zhjx-redis

  ly-ac-rtc-svc:
    image: zhjx-images.tencentcloudcr.com/ly-sky.com/ly-ac-rtc-svc:latest
    init: true
    restart: unless-stopped
    environment: *svc-environment
    networks:
      - zhjx-network
    entrypoint: [""]
    command: ["sh", "-c", "java -Xms1G -Xmx2G -XX:MaxMetaspaceSize=256M -XX:+UseG1GC -XX:MaxGCPauseMillis=200 -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/tmp -XX:+UseStringDeduplication -jar -Dfile.encoding=UTF-8 -Duser.timezone=Asia/Shanghai /usr/local/app.jar"]
    depends_on:
      - zhjx-nacos
      - zhjx-redis

  ly-ac-course-svc:
    image: zhjx-images.tencentcloudcr.com/ly-sky.com/ly-ac-course-svc:latest
    init: true
    hostname: ly-ac-course-svc
    restart: unless-stopped
    environment: *svc-environment
    networks:
      - zhjx-network
    entrypoint: [""]
    command: ["sh", "-c", "java -Xms1G -Xmx2G -XX:MaxMetaspaceSize=256M -XX:+UseG1GC -XX:MaxGCPauseMillis=200 -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/tmp -XX:+UseStringDeduplication -jar /usr/local/app.jar"]
    depends_on:
      - zhjx-nacos
      - zhjx-redis

  ly-ac-classroom-svc:
    image: zhjx-images.tencentcloudcr.com/ly-sky.com/ly-ac-classroom-svc:latest
    init: true
    hostname: ly-ac-classroom-svc
    restart: unless-stopped
    environment: *svc-environment
    networks:
      - zhjx-network
    entrypoint: [""]
    command: ["sh", "-c", "java -Xms1G -Xmx2G -XX:MaxMetaspaceSize=256M -XX:+UseG1GC -XX:MaxGCPauseMillis=200 -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/tmp -XX:+UseStringDeduplication -jar /usr/local/app.jar"]
    depends_on:
      - zhjx-nacos
      - zhjx-redis

  # 平台
  ly-ac-client-ui:
    image: zhjx-images.tencentcloudcr.com/ly-sky.com/ly-ac-client-ui:latest
    init: true
    restart: unless-stopped
    environment: *ui-environment
    networks:
      - zhjx-network
    depends_on:
      - zhjx-nacos

  # 课中
  ly-ac-live-ui:
    image: zhjx-images.tencentcloudcr.com/ly-sky.com/ly-ac-live-ui:latest
    init: true
    restart: unless-stopped
    environment: *ui-environment
    networks:
      - zhjx-network
    depends_on:
      - zhjx-nacos

  # H5
  ly-ac-ykt-mobile-ui:
    image: zhjx-images.tencentcloudcr.com/ly-sky.com/ly-ac-ykt-mobile-ui:latest
    init: true
    restart: unless-stopped
    environment: *ui-environment
    networks:
      - zhjx-network
    depends_on:
      - zhjx-nacos

  # 互动中心
  ly-ac-interaction-tool-svc:
    image: zhjx-images.tencentcloudcr.com/ly-sky.com/ly-ac-interaction-tool-svc:latest
    init: true
    restart: unless-stopped
    environment: *svc-environment
    networks:
      - zhjx-network
    entrypoint: [ "" ]
    command: [ "sh", "-c", "java -Xms1G -Xmx2G -XX:MaxMetaspaceSize=256M -XX:+UseG1GC -XX:MaxGCPauseMillis=200 -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/tmp -XX:+UseStringDeduplication -jar /usr/local/app.jar" ]
    depends_on:
      - zhjx-nacos

  ly-ac-resource-svc:
    image: zhjx-images.tencentcloudcr.com/ly-sky.com/ly-ac-resource-svc:latest
    init: true
    restart: unless-stopped
    environment: *svc-environment
    networks:
      - zhjx-network
    entrypoint: [ "" ]
    command: [ "sh", "-c", "java -Xms1G -Xmx2G -XX:MaxMetaspaceSize=256M -XX:+UseG1GC -XX:MaxGCPauseMillis=200 -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/tmp -XX:+UseStringDeduplication -jar /usr/local/app.jar" ]
    depends_on:
      - zhjx-nacos

networks:
  zhjx-network:
    external: true
