services:
  mysql:
    image: mysql:8.4.7
    container_name: zhjx-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: LianYi@123
    networks:
      - zhjx-network
    ports:
      - 3306:3306
    volumes:
      - /opt/1panel/docker/compose/zhjx-mysql/data:/var/lib/mysql
      - /opt/1panel/docker/compose/zhjx-mysql/conf/my.cnf:/etc/my.cnf
      - /opt/1panel/docker/compose/zhjx-mysql/log:/var/log/mysql
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    labels:
      createdBy: "Apps"
networks:
  zhjx-network:
    external: true