{% if RUN_ZHJX_ZLMEDIAKIT %}
services:
  zhjx-permissions:
    volumes:
      - ../../data/zlmediakit/conf:/mounts/zlmediakit/conf
      - ../../data/zlmediakit/log:/mounts/zlmediakit/log
      - ../../data/zlmediakit/www:/mounts/zlmediakit/www

  zhjx-zlmediakit:
    image: "{{ EDOPS_ZLMEDIAKIT_IMAGE }}"
    init: true
    hostname: zhjx-zlmediakit
    restart: unless-stopped
    user: "1000:1000"
    ports:
      - "8080:80"
      - "554:554"
      - "1935:1935"
      - "30000-30100:30000-30100"
    volumes:
      - ../../data/zlmediakit/conf:/opt/media/conf
      - ../../data/zlmediakit/log:/opt/media/log
      - ../../data/zlmediakit/www:/opt/media/www
    networks:
      - {{ EDOPS_NETWORK_NAME }}
    depends_on:
      - zhjx-permissions
{% endif %}
