version: "3.8"

x-ui-environment:
  &ui-environment
  spring.cloud.inetutils.preferred-networks: 10.10.0
  API_GATEWAY_URL: http://ly-ac-gateway-svc:50000 
  SCHOOL_ID: ${SCHOOL_ID}
  API_TENANT_URL: http://${MASTER_NODE_IP}:50004
  API_OBJECT_STORAGE_URL: http://${MASTER_NODE_IP}:50007
  ISPOT_APP_SOURCE: U2FsdGVkX1+uTHJpKPc3BiX/9YDbAbwQ8j+2T7+/IvtTcbmT3oq6XQNkx4qIdnVwdX79Ol23CoEfjY7V7g7kj8If8I1P2j6MK+7cKEkwCrg57dKFH1tuhzPeTtP6YSbN
  
x-svc-environment:
  &svc-environment
  discovery: zhjx-nacos
  nacosGroup: DEFAULT_GROUP
  mysqlHost: ${MASTER_NODE_IP}
  mysqlPort: 3306
  mysqlUser: root
  mysqlPassword: LianYi@123
  serverAddr: http://zhjx-nacos:8848


services:
  # 产教融合web端
  ly-ac-ilive-ecom-ui:
    image: zhjx-images.tencentcloudcr.com/ly-sky.com/ly-ac-ilive-ecom-ui:${VERSION_UI_ILIVE}
    init: true
    environment: *ui-environment
    networks:
      - zhjx-network

  ly-ac-ilive-ecom-tab-svc:
    image: zhjx-images.tencentcloudcr.com/ly-sky.com/ly-ac-ilive-ecom-tab-svc:${VERSION_SVC_DEFAULT}
    environment: *svc-environment
    networks:
      - zhjx-network
    entrypoint: [ "" ]
    command: [ "sh", "-c", "java -Xms1G -Xmx2G -XX:MaxMetaspaceSize=256M -XX:+UseG1GC -XX:MaxGCPauseMillis=200 -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/tmp -XX:+UseStringDeduplication -jar /usr/local/app.jar" ]

networks:
  zhjx-network:
    external: true