CMS_OAUTH2_SECRET: cCf8o5TGU7LoOGN1ZVIgE9R7
EDOPS_ELASTICSEARCH_PASSWORD: Oaon1LUsNq6S
EDOPS_ENABLED_MODULES:
- zhjx_zlmediakit
EDOPS_ISPOT_APP_SOURCE: v9wsePOjui4ZqjHv4vCBpyfqKK1P3MhWtQRpHGA49CR2nNK7LaIEgzhd73bKYLhn
EDOPS_MASTER_NODE_IP: 192.168.0.2
EDOPS_MINIO_ROOT_PASSWORD: ErqOl4kwLwcg
EDOPS_MQTT_ACCOUNT_PASSWORD: laPsLMZxxohJ
EDOPS_MQTT_PASSWORD: SWXfn0JcSCIx
EDOPS_MYSQL_ROOT_PASSWORD: STj1ZAHGUYJS
EDOPS_RABBITMQ_DEFAULT_PASS: LUPwgc3qoGIT
EDOPS_TENANT_SECRET_KEY: tztlMhpHzUrh2yTAkJVQdMub0eSo9kFSM47R7J8AQ7XT4378n0zOcKR8UrSSxcwq
EDOPS_ZLM_SECRET: hLZhzG69w9QU8ODzj3LtmPw4IWurIyMJ
ID: onZJpsdPWdBPyYkYptudnXEN
JWT_RSA_PRIVATE_KEY: '-----BEGIN RSA PRIVATE KEY-----

  MIIEoAIBAAKCAQEArkNHhY1pZI1LGugNkPjMo6KP2UHv+j9pzrhn5FGvnBbJc79G

  eWeA0tzpBwEt6R+6TDWzpJizUbB/0Tc972HS0f9vOYgPmeXID1K/vitm7VQfabfM

  f2bvM2hRbYczx3j4Al3t2pq8X/mkwiclDg1lyxY6ekF2W1Xok3QNv6dwSi7EcoKj

  urVeW4iHYcDjFy9B/RCgoBFdXqNQ3H5gjfrJ/T8MrBst+z2VMlajA3ylZAXGgEit

  T708pLwR5zsnYk7lTYWH2SZS2+y+shTwNa1cthTEtQQKoV/RjO3gY16/BHMNcj20

  mXo5ch/xtsmJn/iL8FVTPoAXXsHd7TL8SJZKcQIDAQABAoH/LvfzTwvOXEu48oeZ

  IHnuriwimWwsQkbVPeJ2HhPmQSvjIE9tr0s2bZ8dL8YhmbPzgpb21GZT7rCjwsAg

  8WRsbi1qzRbfHZvRUE/9XkRUeaMy1Eu10qDr1+9GAz9ttVXlgr3OXh1WqIeg4LOs

  SR1TUmmrWUhLnlKJXTTqf72hhlyimJn+aPAT8pIJDDeo7VTF5V9WS8ECgFSX+lda

  OujmKI2hS2J2LRlwqm7sixXRB7znqz5Z+lYK0EuwveogJB2yoytHw2Oh52OW3cF1

  s1f/1JHiwXyMv8KL38AgdxND4AJoYfgLtRncH/L+ngU7vUmGh1CPWtuRP835Vfrv

  qzM1AoGBAMk9BE28RVau5nUeIt55oPV6yMJw/OznCjHKbxsZBlSQE6kL/V2HgDxQ

  nGl+GvVLrrFxN074Ejj09s2Y1LLo1TUYy7ENrYkUzR9NnrMzNKWlvCKPdlN1LKEA

  W14Qpcw93NwAl1EZXD7fDozRvueqoiqh2uX1truNynWmCxKKL8h3AoGBAN2vDNfO

  daPtApk++CV4fNxco8G7ukL/nHquIJirolsz1tc0d8M9t1nAzkwomAFKOaQ+v6tv

  FoiyOh8Qyx7vTcOr8cvqYQ8u7Y+a1X4Zdh5NTo5jPqsrDP33EKaf4sK6cArjRFXc

  U4a44LggWRmS8TktrgpWE9mQg5CRh14PhKZXAoGABY4CnWax/0eKovb2/W8cC0qd

  WgimYp+p/1/YG0Zgj1r+v+7NypQf7QpIlvzdH6I8Kze10B822Y2hdmFelaWppPKP

  RM7c2GjTlKae19F1BZGClO2i1YDpf3Q0EW+iM/YNL6Fwi9OIYU/k5ewwOdLS8RxQ

  n4JdzeWHDiJMMfHQidcCgYAvytp4+DDSi3lg8ntrEKPSmkJPtRo98X+Zz0qFv5L8

  GJv7v3sGY5rQxcl0D9hdhtQQfdqyqftwswPmyKcR30OjqMEzVi9gp5xdtmLKkdCu

  Tbpe5jSPkHN3mTlEwvmPQ8R+BGsqG5sCU39XEtpCsjRBQIDiB5a18/r5QvatJ6lQ

  dwKBgAQkOfEaNfkLVUz8qqCFl8DHPRWtN06vufYr22D2gQCPDlYURikoPV5QqDTI

  3JkEqhJyEswHMaG9rJyJUI1+YYScTe/ZpJXJ/Y7aVzdE3ctj3sfBm0NkHvk+HhRr

  65REHASuLfG3H+YP3g9kg8AROmdZ5DQ+YJud3birJNqz6iqQ

  -----END RSA PRIVATE KEY-----'
MEILISEARCH_API_KEY: c1ebfac8412d1d038b8574004e71a63a1399b8d13f3434c7dd19d119844a3d51
MEILISEARCH_API_KEY_UID: 4d17fc12-d832-498a-a884-280de7c65afe
MEILISEARCH_MASTER_KEY: Tjgcpmkvopw1z7F9aAI25K2g
MYSQL_ROOT_PASSWORD: uDl4rgWV
OPENEDX_MYSQL_PASSWORD: VxKJ4llX
OPENEDX_SECRET_KEY: zdi2zl6wUxc73adRfrIPqcPP
PLUGINS:
- mfe
- indigo
PLUGIN_INDEXES:
- https://overhang.io/tutor/main
- https://overhang.io/tutor/contrib
